-- Création de la base de données

-- Table pour les entités
CREATE TABLE entities (
    entity_id SERIAL PRIMARY KEY,
    entity_name VARCHAR(50) NOT NULL
);

-- Table pour les questions QCM
CREATE TABLE qcm_questions (
    question_id SERIAL PRIMARY KEY,
    entity_id INT,
    question_text TEXT NOT NULL,
    FOREIGN KEY (entity_id) REFERENCES entities(entity_id)
);

-- Table pour les options de réponse
CREATE TABLE qcm_options (
    option_id SERIAL PRIMARY KEY,
    question_id INT,
    option_text VARCHAR(255) NOT NULL,
    is_correct BOOLEAN NOT NULL,
    FOREIGN KEY (question_id) REFERENCES qcm_questions(question_id)
);

-- Insertion des entités
INSERT INTO entities (entity_name) VALUES
('IT'),
('Commercial'),
('RH'),
('Finance'),
('Marketing');

-- Insertion des QCM pour chaque entité
-- QCM pour IT
INSERT INTO qcm_questions (entity_id, question_text) VALUES
(1, 'Quels sont les avantages principaux de l''utilisation d''un modèle MVC dans le développement web ?'),
(1, 'Quelles sont les techniques utilisées pour prévenir les attaques par injection SQL ?'),
(1, 'Quels protocoles sont utilisés pour sécuriser les communications sur Internet ?'),
(1, 'Quels sont les principes fondamentaux de l''agilité selon le Manifeste Agile ?'),
(1, 'Quels sont les types de bases de données relationnelles ?'),
(1, 'Quels sont les avantages de l''utilisation des conteneurs comme Docker ?'),
(1, 'Quels sont les objectifs principaux de la méthode DevOps ?'),
(1, 'Quels langages sont couramment utilisés pour le développement web côté client ?'),
(1, 'Quels sont les risques associés à une mauvaise gestion des dépendances dans un projet logiciel ?'),
(1, 'Quelles sont les étapes clés du cycle de vie du développement logiciel (SDLC) ?');

INSERT INTO qcm_options (question_id, option_text, is_correct) VALUES
(1, 'Réduction de la taille du code', FALSE),
(1, 'Séparation des préoccupations (logique, interface, données)', TRUE),
(1, 'Augmentation de la vitesse d''exécution', FALSE),
(1, 'Meilleure modularité et maintenance', TRUE),
(2, 'Utilisation de pare-feu', FALSE),
(2, 'Requêtes paramétrées', TRUE),
(2, 'Validation des entrées utilisateur', TRUE),
(2, 'Augmentation de la bande passante', FALSE),
(3, 'FTP', FALSE),
(3, 'HTTPS', TRUE),
(3, 'SSH', TRUE),
(3, 'SMTP', FALSE),
(4, 'Collaboration et communication continues', TRUE),
(4, 'Automatisation des tests', TRUE),
(4, 'Optimisation des profits', FALSE),
(4, 'Réduction des effectifs', FALSE),
(5, 'MySQL', TRUE),
(5, 'MongoDB', FALSE),
(5, 'PostgreSQL', TRUE),
(5, 'Redis', FALSE),
(6, 'Portabilité des applications', TRUE),
(6, 'Augmentation des coûts matériels', FALSE),
(6, 'Isolation des environnements', TRUE),
(6, 'Complexité accrue du code', FALSE),
(7, 'Amélioration de la collaboration entre développement et opérations', TRUE),
(7, 'Réduction du temps de mise sur le marché', TRUE),
(7, 'Augmentation des coûts de maintenance', FALSE),
(7, 'Centralisation des données', FALSE),
(8, 'JavaScript', TRUE),
(8, 'Python', FALSE),
(8, 'HTML/CSS', TRUE),
(8, 'SQL', FALSE),
(9, 'Conflits de versions', TRUE),
(9, 'Augmentation de la sécurité', FALSE),
(9, 'Retards dans les déploiements', TRUE),
(9, 'Réduction des coûts', FALSE),
(10, 'Analyse des besoins', TRUE),
(10, 'Conception', TRUE),
(10, 'Marketing du produit', FALSE),
(10, 'Maintenance', TRUE);

-- QCM pour Commercial
INSERT INTO qcm_questions (entity_id, question_text) VALUES
(2, 'Quels sont les éléments clés d''une stratégie de vente consultative ?'),
(2, 'Quels outils sont essentiels pour la gestion des relations client ?'),
(2, 'Quels indicateurs mesurent la performance commerciale ?'),
(2, 'Quels sont les avantages d''une segmentation de marché ?'),
(2, 'Quelles sont les étapes du processus de vente ?'),
(2, 'Quels sont les types de canaux de distribution ?'),
(2, 'Quelles sont les techniques de négociation efficaces ?'),
(2, 'Quels sont les objectifs d''une campagne de prospection ?'),
(2, 'Quels facteurs influencent la fidélité des clients ?'),
(2, 'Quels sont les avantages de l''analyse des données commerciales ?');

INSERT INTO qcm_options (question_id, option_text, is_correct) VALUES
(11, 'Identifier les besoins du client', TRUE),
(11, 'Proposer des solutions adaptées', TRUE),
(11, 'Vendre le produit le moins cher', FALSE),
(11, 'Automatiser les ventes', FALSE),
(12, 'CRM (Customer Relationship Management)', TRUE),
(12, 'ERP (Enterprise Resource Planning)', FALSE),
(12, 'Logiciels de comptabilité', FALSE),
(12, 'Outils d''automatisation marketing', TRUE),
(13, 'NPS (Net Promoter Score)', TRUE),
(13, 'ROI (Return on Investment)', TRUE),
(13, 'Taux de conversion', TRUE),
(13, 'Nombre d''employés', FALSE),
(14, 'Meilleure compréhension des clients', TRUE),
(14, 'Réduction des coûts publicitaires', FALSE),
(14, 'Ciblage plus précis', TRUE),
(14, 'Augmentation des effectifs', FALSE),
(15, 'Prospection', TRUE),
(15, 'Négociation', TRUE),
(15, 'Clôture', TRUE),
(15, 'Production', FALSE),
(16, 'Vente directe', TRUE),
(16, 'Vente en ligne', TRUE),
(16, 'Vente par correspondance', TRUE),
(16, 'Vente interne', FALSE),
(17, 'Écoute active', TRUE),
(17, 'Proposition de valeur claire', TRUE),
(17, 'Augmentation des prix', FALSE),
(17, 'Flexibilité', TRUE),
(18, 'Augmenter le chiffre d''affaires', TRUE),
(18, 'Identifier de nouveaux clients', TRUE),
(18, 'Réduire les coûts', FALSE),
(18, 'Améliorer la logistique', FALSE),
(19, 'Qualité du service', TRUE),
(19, 'Expérience client', TRUE),
(19, 'Prix compétitifs', TRUE),
(19, 'Taille de l''entreprise', FALSE),
(20, 'Prise de décision éclairée', TRUE),
(20, 'Optimisation des campagnes', TRUE),
(20, 'Réduction des effectifs', FALSE),
(20, 'Augmentation des bénéfices', TRUE);

-- QCM pour RH
INSERT INTO qcm_questions (entity_id, question_text) VALUES
(3, 'Quels sont les objectifs de la Gestion Prévisionnelle des Emplois et des Compétences (GPEC) ?'),
(3, 'Quels documents sont obligatoires lors de l''embauche en France ?'),
(3, 'Quels sont les avantages d''un plan de formation continue ?'),
(3, 'Quelles sont les composantes d''une politique de rémunération ?'),
(3, 'Quels sont les indicateurs clés de performance RH ?'),
(3, 'Quelles sont les étapes du processus de recrutement ?'),
(3, 'Quels sont les risques liés à une mauvaise gestion des conflits en entreprise ?'),
(3, 'Quels sont les avantages de la diversité en milieu de travail ?'),
(3, 'Quelles lois régissent la protection des données personnelles des employés en Europe ?'),
(3, 'Quels sont les objectifs d''une évaluation annuelle des performances ?');

INSERT INTO qcm_options (question_id, option_text, is_correct) VALUES
(21, 'Anticiper les besoins en compétences', TRUE),
(21, 'Réduire les effectifs', FALSE),
(21, 'Planifier les évolutions de carrière', TRUE),
(21, 'Automatiser les processus RH', FALSE),
(22, 'Contrat de travail', TRUE),
(22, 'Attestation de formation', FALSE),
(22, 'Déclaration préalable à l''embauche', TRUE),
(22, 'CV', FALSE),
(23, 'Amélioration des compétences', TRUE),
(23, 'Augmentation de la productivité', TRUE),
(23, 'Réduction des congés', FALSE),
(23, 'Engagement des employés', TRUE),
(24, 'Salaire de base', TRUE),
(24, 'Avantages en nature', TRUE),
(24, 'Primes', TRUE),
(24, 'Réduction des coûts', FALSE),
(25, 'Taux de rétention des employés', TRUE),
(25, 'Taux d''absentéisme', TRUE),
(25, 'Chiffre d''affaires', FALSE),
(25, 'Satisfaction des employés', TRUE),
(26, 'Rédaction de l''offre d''emploi', TRUE),
(26, 'Sélection des candidats', TRUE),
(26, 'Intégration', TRUE),
(26, 'Marketing produit', FALSE),
(27, 'Baisse de la productivité', TRUE),
(27, 'Démotivation des équipes', TRUE),
(27, 'Augmentation des ventes', FALSE),
(27, 'Turnover élevé', TRUE),
(28, 'Innovation accrue', TRUE),
(28, 'Meilleure prise de décision', TRUE),
(28, 'Réduction des coûts', FALSE),
(28, 'Satisfaction des clients', TRUE),
(29, 'RGPD', TRUE),
(29, 'Code du travail', TRUE),
(29, 'Loi sur la cybersécurité', FALSE),
(29, 'Directive e-Privacy', TRUE),
(30, 'Identifier les forces et faiblesses', TRUE),
(30, 'Fixer des objectifs', TRUE),
(30, 'Réduire les salaires', FALSE),
(30, 'Planifier les promotions', TRUE);

-- QCM pour Finance
INSERT INTO qcm_questions (entity_id, question_text) VALUES
(4, 'Quels sont les éléments principaux d''un bilan comptable ?'),
(4, 'Quels sont les ratios financiers clés pour évaluer la santé d''une entreprise ?'),
(4, 'Quels sont les objectifs de l''analyse financière ?'),
(4, 'Quels sont les types de budgets en entreprise ?'),
(4, 'Quelles sont les sources de financement pour une entreprise ?'),
(4, 'Quels sont les principes comptables généralement acceptés (PCGA) ?'),
(4, 'Quels sont les avantages de la gestion de la trésorerie ?'),
(4, 'Quelles sont les conséquences d''une mauvaise gestion financière ?'),
(4, 'Quels sont les outils d''analyse financière ?'),
(4, 'Quels sont les types de coûts en comptabilité ?');

INSERT INTO qcm_options (question_id, option_text, is_correct) VALUES
(31, 'Actif', TRUE),
(31, 'Passif', TRUE),
(31, 'Chiffre d''affaires', FALSE),
(31, 'Capitaux propres', TRUE),
(32, 'Ratio d''endettement', TRUE),
(32, 'Ratio de liquidité', TRUE),
(32, 'Taux de conversion', FALSE),
(32, 'Marge brute', TRUE),
(33, 'Évaluer la rentabilité', TRUE),
(33, 'Analyser la solvabilité', TRUE),
(33, 'Augmenter les ventes', FALSE),
(33, 'Prévoir les performances futures', TRUE),
(34, 'Budget opérationnel', TRUE),
(34, 'Budget d''investissement', TRUE),
(34, 'Budget marketing', TRUE),
(34, 'Budget RH', FALSE),
(35, 'Fonds propres', TRUE),
(35, 'Emprunts bancaires', TRUE),
(35, 'Subventions', TRUE),
(35, 'Ventes de produits', FALSE),
(36, 'Principe de prudence', TRUE),
(36, 'Principe de continuité', TRUE),
(36, 'Principe de non-compensation', TRUE),
(36, 'Principe de surévaluation', FALSE),
(37, 'Éviter les problèmes de liquidité', TRUE),
(37, 'Optimiser les investissements', TRUE),
(37, 'Réduire les effectifs', FALSE),
(37, 'Améliorer la planification', TRUE),
(38, 'Insolvabilité', TRUE),
(38, 'Pertes financières', TRUE),
(38, 'Augmentation des ventes', FALSE),
(38, 'Mauvaise réputation', TRUE),
(39, 'Tableau de flux de trésorerie', TRUE),
(39, 'Analyse SWOT', FALSE),
(39, 'Ratios financiers', TRUE),
(39, 'Compte de résultat', TRUE),
(40, 'Coûts fixes', TRUE),
(40, 'Coûts variables', TRUE),
(40, 'Coûts directs', TRUE),
(40, 'Coûts marketing', FALSE);

-- QCM pour Marketing
INSERT INTO qcm_questions (entity_id, question_text) VALUES
(5, 'Quels sont les objectifs principaux du marketing de contenu ?'),
(5, 'Quelles sont les composantes du mix marketing (4P) ?'),
(5, 'Quels sont les avantages du SEO (optimisation pour les moteurs de recherche) ?'),
(5, 'Quels sont les rôles des personas en marketing ?'),
(5, 'Quels sont les types de campagnes publicitaires digitales ?'),
(5, 'Quelles sont les métriques clés pour évaluer une campagne marketing ?'),
(5, 'Quels sont les avantages des réseaux sociaux pour le marketing ?'),
(5, 'Quelles sont les étapes du parcours client ?'),
(5, 'Quels sont les outils d''automatisation marketing ?'),
(5, 'Quels sont les principes de l''inbound marketing ?');

INSERT INTO qcm_options (question_id, option_text, is_correct) VALUES
(41, 'Attirer une audience', TRUE),
(41, 'Engager les clients', TRUE),
(41, 'Réduire les coûts', FALSE),
(41, 'Fidéliser les clients', TRUE),
(42, 'Produit', TRUE),
(42, 'Prix', TRUE),
(42, 'Promotion', TRUE),
(42, 'Performance', FALSE),
(43, 'Augmentation du trafic organique', TRUE),
(43, 'Amélioration du classement dans les moteurs de recherche', TRUE),
(43, 'Réduction des coûts publicitaires', TRUE),
(43, 'Automatisation des ventes', FALSE),
(44, 'Définir les profils des clients cibles', TRUE),
(44, 'Personnaliser les campagnes', TRUE),
(44, 'Réduire les budgets', FALSE),
(44, 'Analyser les performances', TRUE),
(45, 'Publicité display', TRUE),
(45, 'Publicité sur les réseaux sociaux', TRUE),
(45, 'Publicité par e-mail', TRUE),
(45, 'Publicité imprimée', FALSE),
(46, 'Taux de clics (CTR)', TRUE),
(46, 'Taux de conversion', TRUE),
(46, 'Nombre d''employés', FALSE),
(46, 'Coût par acquisition (CPA)', TRUE),
(47, 'Visibilité accrue', TRUE),
(47, 'Engagement avec les clients', TRUE),
(47, 'Réduction des coûts marketing', FALSE),
(47, 'Interaction en temps réel', TRUE),
(48, 'Prise de conscience', TRUE),
(48, 'Considération', TRUE),
(48, 'Décision', TRUE),
(48, 'Production', FALSE),
(49, 'HubSpot', TRUE),
(49, 'Mailchimp', TRUE),
(49, 'SAP', FALSE),
(49, 'Marketo', TRUE),
(50, 'Attirer avec du contenu pertinent', TRUE),
(50, 'Convertir les prospects', TRUE),
(50, 'Fidéliser les clients', TRUE),
(50, 'Réduire les effectifs', FALSE);